id: 08b60b90-e43d-4b5a-8524-13aee1d056f3
version: -1
name: VMRay-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6fd546dd-976e-4ffe-8e1d-3c210746efde
    type: start
    task:
      id: 6fd546dd-976e-4ffe-8e1d-3c210746efde
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 3efb79a4-ddea-499b-8828-d01ca0788d00
    type: regular
    task:
      id: 3efb79a4-ddea-499b-8828-d01ca0788d00
      version: -1
      name: Get file
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/Inline_malicious.eml
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 763d67e6-5d0d-4d3b-8afa-e153a390398f
    type: playbook
    task:
      id: 763d67e6-5d0d-4d3b-8afa-e153a390398f
      version: -1
      name: Detonate File - VMRay
      description: Detonating file with VMRay
      playbookName: Detonate File - VMRay
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "4"
      - "5"
      - "8"
    scriptarguments:
      File:
        simple: ${File}
      interval:
        simple: "1"
      timeout:
        simple: "10"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 99d88d47-0035-4c52-83cc-a4f507a9783f
    type: regular
    task:
      id: 99d88d47-0035-4c52-83cc-a4f507a9783f
      version: -1
      name: Get analysis by sample
      description: Get all analysis details about a specific sample.
      script: '|||vmray-get-analysis-by-sample'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      limit:
        simple: "1"
      sample_id:
        simple: ${VMRay.Jobs.SampleID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 6df0f771-6420-4042-8cc4-684d2f946cb5
    type: regular
    task:
      id: 6df0f771-6420-4042-8cc4-684d2f946cb5
      version: -1
      name: get-threat-indicators
      description: Get threat indicators (VTI)
      script: '|||vmray-get-threat-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      sample_id:
        simple: ${VMRay.Analysis.SampleID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 74b953f7-83a8-4f3f-8297-d631b830bccd
    type: regular
    task:
      id: 74b953f7-83a8-4f3f-8297-d631b830bccd
      version: -1
      name: Get IOCs
      description: getting iocs of given sample
      script: '|||vmray-get-iocs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      sample_id:
        simple: ${VMRay.Samples.SampleID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 2d23161b-a44a-4170-896d-4458f4af0ab9
    type: regular
    task:
      id: 2d23161b-a44a-4170-896d-4458f4af0ab9
      version: -1
      name: Add tag
      description: Adds a tag to analysis and/or submission
      script: '|||vmray-add-tag'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      analysis_id:
        simple: ${VMRay.Analysis.AnalysisID}
      submission_id:
        simple: ${VMRay.Submissions.SubmissionID}
      tag:
        simple: test_tag
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: d55d0f83-3389-4b1c-8beb-8e345a812c17
    type: regular
    task:
      id: d55d0f83-3389-4b1c-8beb-8e345a812c17
      version: -1
      name: Remove tag
      description: Delete tags from analysis and/or submission
      script: '|||vmray-delete-tag'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      analysis_id:
        simple: ${VMRay.Analysis.AnalysisID}
      submission_id:
        simple: ${VMRay.Submissions.SubmissionID}
      tag:
        simple: test_tag
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 3a898722-da75-4a0a-8144-b246dbb56a4f
    type: regular
    task:
      id: 3a898722-da75-4a0a-8144-b246dbb56a4f
      version: -1
      name: Get Job by sample
      description: Get all jobs details about a specific sample.
      script: '|||vmray_get_job_sample'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      sample_id:
        simple: ${VMRay.Jobs.SampleID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: f7dad3be-ab06-498b-893a-073fc06ff7a2
    type: title
    task:
      id: f7dad3be-ab06-498b-893a-073fc06ff7a2
      version: -1
      name: Test end
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 93bea8bc-3b81-4184-8ea7-bcdf04a90d27
    type: regular
    task:
      id: 93bea8bc-3b81-4184-8ea7-bcdf04a90d27
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 1.0
